### ISSUE TITLE
Will the data be released?

### ISSUE THREAD

**Issue by zig-kwin-hu** [limteng-rpi/fet#1]
Hi, I notice that your input data format is self-defined. Could you release your training data and the arguments you use for training?

**Comment by limteng-rpi** [comment]
I'll update the repo soon to document the code and add a README.
Data sets used for our experiments can be downloaded at:
- FIGER: https://github.com/xiaoling/figer
- KNET: https://github.com/thunlp/KNET
- OntoNotes: https://homes.cs.washington.edu/~eunsol/open_entity.html
- BBN: https://catalog.ldc.upenn.edu/LDC2005T33
