### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by YebowenHu** [limteng-rpi/fet#2]
I tried to use Bert embedding(dim: 768) in this task. And find out CUDA out of memory error in the first epoch even batch size was set to 3. 
May I ask how much GPU memory need to be allocated when you use elmo embeddings and what is the common batch_size you usually use in this task? 

Thanks a lot!

**Comment by limteng-rpi** [comment]
We use ELMo in our experiments and our GPU memory is 16GB. The batch size is 200.
If you use BERT, you probably need to reduce the batch size and accumulate gradients from multiple batches (https://discuss.pytorch.org/t/why-do-we-need-to-set-the-gradients-manually-to-zero-in-pytorch/4903/20).

**Comment by limteng-rpi** [comment]
Also set the max sequence length to a smaller number, e.g., 128.

**Comment by YebowenHu** [comment]
Accumulate gradients might be a good solution. I will give it a try. Thanks! :)
