### ISSUE TITLE
why can't I find the relevant dataset

### ISSUE THREAD

**Issue by nyhDudu** [limteng-rpi/fet#3]
why can't I find the relevant dataset

**Comment by limteng-rpi** [comment]
Could you please elaborate your question?
For datasets, please check this thread: https://github.com/limteng-rpi/fet/issues/1#issuecomment-567624646

**Comment by nyhDudu** [comment]
Thank you very much, I want to know when you will put your dataset on github

**Comment by limteng-rpi** [comment]
We didn't propose new data sets in our paper. All data sets used in the paper can be found here https://github.com/limteng-rpi/fet/issues/1#issuecomment-567624646
