### ISSUE TITLE
cannot achieve the performance in the paper

### ISSUE THREAD

**Issue by YaNjIeE** [limteng-rpi/fet#4]
Hi,

Following your guidance in README.md, I run this code on the OntoNotes datasets by:
python train.py --train /path/to/data/buffer/train --dev /path/to/data/buffer/dev 
--test /path/to/data/buffer/test --ontology /path/to/data/type.txt --output /path/to/output
--elmo_option /path/to/data/eng.original.5.5b.json --elmo_weight /path/to/data/eng.original.5.5b.hdf5 --batch_size 200 --max_epoch 100 --eval_step 200 --gpu

But I can only obtain 
best acc test: 54.25
best mac test: 72.94
best mic test: 67.68

Is there something ignored by me? 
Looking forward to your reply.

Best.

**Comment by limteng-rpi** [comment]
Hi,

For OntoNotes we used the full augmented version developed by Eunsol Choi [1], which contains training data from Gigaword . You probably need to contact her to obtain the data if you have access to Gigaword.

[1] Eunsol Choi, Omer Levy, Yejin Choi, and Luke Zettlemoyer. 2018. Ultra-fine entity typing. In Proceedings of the 56th Annual Meeting of the Association for Computational Linguistics (ACL 2018)

**Comment by YaNjIeE** [comment]
OK, thanks a lot.
